# Generated by Django 4.2.19 on 2025-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("address_street_number", models.IntegerField()),
                ("address_street_name", models.TextField()),
                ("address_apartment_number", models.TextField()),
                ("address_zipcode", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party", models.TextField()),
                ("precinct_number", models.TextField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
