# Generated by Django 4.2.19 on 2025-04-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0004_alter_voter_v20state_alter_voter_v21primary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.BooleanField(),
        ),
    ]
