# Generated by Django 4.2.19 on 2025-04-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_favoritegame"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteGame",
            new_name="FavoriteVideoGame",
        ),
    ]
