# Generated by Django 4.2.19 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_rename_favoritegame_favoritevideogame"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogamelist",
            name="name",
            field=models.TextField(blank=True),
        ),
    ]
