# Generated by Django 4.2.18 on 2025-02-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(blank=True)),
                ("last_name", models.TextField(blank=True)),
                ("city", models.TextField(blank=True)),
                ("email", models.TextField(blank=True)),
                ("image_url", models.TextField(blank=True)),
            ],
        ),
    ]
